package com.example.liftnotes.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006878)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA1EFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F25)
val md_theme_light_secondary = Color(0xFF4A6268)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7EE)
val md_theme_light_onSecondaryContainer = Color(0xFF051F24)
val md_theme_light_tertiary = Color(0xFF545D7E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF111A37)
val md_theme_light_error = Color(0xFFBA1B1B)
val md_theme_light_errorContainer = Color(0xFFFFFFFF)
val md_theme_light_onError = Color(0xFFFFDAD4)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFFBFDFE)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFBFDFE)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF70797B)

val md_theme_dark_primary = Color(0xFF52D7F0)
val md_theme_dark_onPrimary = Color(0xFF00363F)
val md_theme_dark_primaryContainer = Color(0xFF004E5A)
val md_theme_dark_onPrimaryContainer = Color(0xFFA1EFFF)
val md_theme_dark_secondary = Color(0xFFB2CBD1)
val md_theme_dark_onSecondary = Color(0xFF1C3439)
val md_theme_dark_secondaryContainer = Color(0xFF334B50)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7EE)
val md_theme_dark_tertiary = Color(0xFFBDC5EA)
val md_theme_dark_onTertiary = Color(0xFF262F4D)
val md_theme_dark_tertiaryContainer = Color(0xFF3D4665)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE1FF)
val md_theme_dark_error = Color(0xFFFFB4A9)
val md_theme_dark_errorContainer = Color(0xFF680003)
val md_theme_dark_onError = Color(0xFF930006)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD4)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E4)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFC4C7C7)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899295)